### PR TITLE
Add email anonymizer option in case is needed for GDPR

### PR DESCRIPTION
**Pull request by sdelrio**
* Since rsyslog had Apache License, Version 2.0 I put that too, not an expert on licenses but since is a modification of the original samples I think it should be there.

### CODE REVIEW

**Comment by bokysan** [comment]
Hello Sergio,

thank you so much for this commit. I've looked it over and -- with your permission -- I would like to modify it a bit. 

For example, the regexp for emails is not OK, as it will not catch all valid email addresses - the [possible list is much wider](https://www.mailboxvalidator.com/resources/articles/acceptable-email-address-syntax-rfc/).

I'd also like to limit the number of new environments added (as we already have several) and see if there's a better way to modify `rsyslog.conf`.

I'll leave the PR open but will pull your changes into a separate branch.

**Comment by sdelrio** [comment]
sure!
I think I had a very log regexp for emails long ago but could not find int (it was several lines).

**Comment by bokysan** [comment]
OO, so this is the updated branch: https://github.com/bokysan/docker-postfix/pull/94.

Your comments are welcome.

**Comment by sdelrio** [comment]
Nice!, I've taken a fast look and looks good, there is even a bats test.

**Pull request closed without merging**
