### PR TITLE
Changes to make it work with gmail relay

### PR DESCRIPTION
**Pull request by hongkongkiwi**
I added some useful variables and also added some TLS settings so we can work correctly with gmail.

Also allowed the user to set arbitrary postfix options in an environment variable.

For testing, the user can try docker-compose up -d in the project directory.

### CODE REVIEW

**Comment by bokysan** [comment]
Hi, thank you for the commit.

I've made some comments -- can you look at them and revert back to me.

Thanks.

**Comment by hongkongkiwi** [comment]
Happy to, but I can't seem to see any comments?

**Comment by bokysan** [comment]
Hi,

since you haven't gotten back to me, just wanted to check in if you can see the reviews now?

**Comment by bokysan** [comment]
Since you haven't gotten back to me, I'm going to go ahead and close this pull request.

However I will use your ideas in the new version of the code.

**Pull request closed without merging**
