### PR TITLE
Update ubuntu and sasl_xoauth2 version and add SMPTD_SASL_USERS option

### PR DESCRIPTION
**Pull request by bokysan**

### CODE REVIEW

**Comment by bokysan** [comment]
Hey @vcazsdk your commits look nice -- I'd like to merge them to the main tree, if you've finished with them?

**Comment by vcazsdk** [comment]
Hi @bokysan. Yes i have finished it, tested it and put it in our production. That's work well for me. You can merge to the main tree. Thank you

**Comment by bokysan** [comment]
I have a failure when bulding SASL XOAUTH. Have you run into this issue? https://github.com/bokysan/docker-postfix/runs/8201677523?check_suite_focus=true

**Comment by vcazsdk** [comment]
Yes i got this error with alpine build. At the time, i thought it was my environment that was incorrect. I didn't try to correct this error because I didn't have enough time and we don't use the alpine image. I had build only the amd64 ubuntu image

**Comment by vcazsdk** [comment]
I have pushed new commit that fix alpine build error

**Comment by vcazsdk** [comment]
Definitely, the alpine image is buggy with sasl-xoauth2. Authentication failed with this postfix error :

> 2022-09-06T20:22:06.305850+00:00 INFO    postfix/qmgr[262]: 4995A31DD: from=<noreply@xxxxxx.com>, size=16199, nrcpt=1 (queue active)
> 2022-09-06T20:22:06.511764+00:00 WARNING postfix/qmgr[262]: warning: private/smtp socket: malformed response
> 2022-09-06T20:22:06.511794+00:00 WARNING postfix/qmgr[262]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
> 2022-09-06T20:22:06.511847+00:00 WARNING postfix/master[260]: warning: process /usr/libexec/postfix/smtp pid 597 killed by signal 11
> 2022-09-06T20:22:06.511853+00:00 WARNING postfix/master[260]: warning: /usr/libexec/postfix/smtp: bad command startup -- throttling
> 2022-09-06T20:22:06.521235+00:00 INFO    postfix/error[600]: 4995A31DD: to=<xxxxx@xxxxxxxx.com>, relay=none, delay=0.23, delays=0.02/0.21/0/0.01, dsn=4.3.0, status=deferred (unknown mail transport error)

**Comment by bokysan** [comment]
Hm, that might be the reason I never managed to get integration tests in #43 working. I'll merge this to master and test it out once the compile passes. Most likely will have to give up on sasl-xoauth2 in alpine until this issue is fixed upstream.

Thanks so much for your work!

**Pull request merged**
