### PR TITLE
Include ldap support in docker image

### LINKED ISSUE #204: LDAP lookup map support
I'm working on deploying this in a kubernetes cluster where I'm using a central idp to manage some user/service accounts. Would it be possible to include the `postfix-ldap` package in this docker image to enable the use of ldap lookup for postfix maps?  It's available for both debian and alpine and is under 500kB (68Kb for alpine) so it shouldn't have a large impact on either image.

If you're open to it, i can submit a PR to add it.

### PR DESCRIPTION
**Pull request by pixil98**
Fixes #204

Includes the `postfix-ldap` package in both debian and alpine docker images.

### CODE REVIEW

**Comment by bokysan** [comment]
Hi, looks OK. Tests are successful.

I would suggest:
- updating documentation
- writing some tests 
- moving from DRAFT to FINAL so I can merge.

Cheers,
B

**Comment by pixil98** [comment]
Will do, thanks. I've been sidetracked this week with some unrelated database issues that I need to track down. Once I get that figured out (hopefully tonight) I'll finish this up. In addition I want to fully test that ldap is working with only that package being installed before I undraft it. Last I left it, I was getting an error binding, but I'm pretty sure that's just my config.

**Comment by pixil98** [comment]
I should have some time to work on this over the weekend. What kind of tests are you looking for?  It should be easy enough to test that when an ldap map is configured it doesn't give the error that ldap isn't supported. Doing anything beyond that would require setting up and configuring an ldap server for the test.

**Comment by pixil98** [comment]
You can semi ignore that previous comment, I rewrote the ldap tests to use `postmap` instead of trying to send an email and I verified that it actually fails if ldap isn't working. I still always get successes on the other tests, but that's less of a concern to me since I didn't touch their functionality.

**Comment by pixil98** [comment]
@bokysan can we get this merged in soon?

**Comment by bokysan** [comment]
Yeah, missed it. There we go.

I'll test it out a bit and make a release this week.

**Pull request merged**
