### PR TITLE
Need to set LoadbalancerIP in Service specification. Patch to copy all specs over from Values files.

### PR DESCRIPTION
**Pull request by komasoftware**
I want to copy over loadBalancerIP to grab a predefined static ip. 
This patch copies over all `spec` settings predefined in the values file.

### CODE REVIEW

**Comment by bokysan** [comment]
Thank you for the commit.

Could you please update `values.yml` and `README.md` as well? Otherwise nobody will know about this feature.

Thanks,
B

**Comment by komasoftware** [comment]
Sure, I will do that.

Can I make my forked repo easily function as helm repo by publishing the gh-pages so I can test this out against my fork ?

**Comment by bokysan** [comment]
- clone the repo
- fix your chart
- make test `heml/test_*.yml`
- make sure all tests go through by running `helm/tests.sh`
- install your chart by calling `helm install name ./helm/mail`
- commit

**Comment by komasoftware** [comment]
Everything cleaned up, added a test and updated README.

**Comment by komasoftware** [comment]
Last commit fixes the merge conflict in the README

**Comment by bokysan** [comment]
LGTM.

**Pull request merged**
