### PR TITLE
Add feature to bring your own secret resource

### PR DESCRIPTION
**Pull request by jzandbergen**
Hi this PR seeks to implement functionality to load existing secrets as environment variables in the pod.

The rationale behind this PR:
We use a controller that retrieves secrets from an external system and creates them in kubernetes. This PR would allow us to deploy this helmchart which simply consumes the existing secret provisioned by the controller.

### CODE REVIEW

**Comment by bokysan** [comment]
Hello,

thank you for your commit. Before I merge it, can you be so kind and add test cases as well?

Thank you.

**Comment by jzandbergen** [comment]
Sure! I'm not to familiar with the testing so I hope I did the right thing here.

**Comment by jzandbergen** [comment]
Hi @bokysan , 

Can I politely ask you to have another look at this PR?
Thanks!

**Comment by bokysan** [comment]
Sorry, missed it -- merging now!

**Comment by jzandbergen** [comment]
Absolutely no problem :). Thank you very much for your time. Cheers!

**Pull request merged**
